apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: cc-gateway-service
  name: cc-gateway-service
spec:
  ports:
  - name: 9090-8080
    port: 9090
    protocol: TCP
    targetPort: 8080
  selector:
    app: cc-gateway-service
  type: LoadBalancer
status:
  loadBalancer: {}
