apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: cc-gateway-service
  name: cc-gateway-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cc-gateway-service
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: cc-gateway-service
    spec:
      containers:
      - image: wskyoung/cc-gateway-service
        name: cc-gateway-service
